# Site settings
title: "Dmitriy Strukov CV"
description: "Dmitriy Strukov CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dmitriy Strukov"
resume_title:                   "Ruby Developer"
resume_contact_email:           "dmitriy.strukov@outlook.com"
resume_contact_telephone:       "+7 (985) 735-77-85"
resume_contact_address:         "Russia, Moscow"
resume_header_contact_info: "Russia, Moscow | +7 (985) 735-77-85 | dmitriy.strukov@outlook.com"
resume_header_intro: "<p>Ambitious Ruby Developer with +2 years of experience in a startups environment. Active OpenSource activist and contributor. Team player, I have good communication skills, also I am interested with architecture, highload, functional programming.</p>"

resume_section_experience:      true
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dmitriy-strukov"
  resume_linkedin_url:          "https://www.linkedin.com/in/dmitriy-strukov-4ab450117/"
  resume_website_url:           "https://dmitriy-strukov.github.io/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
